
// This is a condensed version of the standard MML2OMML.XSL stylesheet from Microsoft.
// It is used to transform MathML (generated by KaTeX) into OMML (Office Math Markup Language) for Word.

export const MML2OMML_XSLT = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:mml="http://www.w3.org/1998/Math/MathML">
  <xsl:output method="xml" omit-xml-declaration="yes" indent="no"/>
  <xsl:template match="mml:math">
    <m:oMath>
      <xsl:apply-templates select="*"/>
    </m:oMath>
  </xsl:template>
  <xsl:template match="mml:mi">
    <m:r>
      <m:rPr>
        <m:sty m:val="p"/>
      </m:rPr>
      <m:t><xsl:value-of select="."/></m:t>
    </m:r>
  </xsl:template>
  <xsl:template match="mml:mn">
    <m:r>
      <m:t><xsl:value-of select="."/></m:t>
    </m:r>
  </xsl:template>
  <xsl:template match="mml:mo">
    <m:r>
      <m:t><xsl:value-of select="."/></m:t>
    </m:r>
  </xsl:template>
  <xsl:template match="mml:msup">
    <m:sSup>
      <m:e>
        <xsl:apply-templates select="*[1]"/>
      </m:e>
      <m:sup>
        <xsl:apply-templates select="*[2]"/>
      </m:sup>
    </m:sSup>
  </xsl:template>
  <xsl:template match="mml:msub">
    <m:sSub>
      <m:e>
        <xsl:apply-templates select="*[1]"/>
      </m:e>
      <m:sub>
        <xsl:apply-templates select="*[2]"/>
      </m:sub>
    </m:sSub>
  </xsl:template>
  <xsl:template match="mml:msubsup">
    <m:sSubSup>
      <m:e>
        <xsl:apply-templates select="*[1]"/>
      </m:e>
      <m:sub>
        <xsl:apply-templates select="*[2]"/>
      </m:sub>
      <m:sup>
        <xsl:apply-templates select="*[3]"/>
      </m:sup>
    </m:sSubSup>
  </xsl:template>
  <xsl:template match="mml:mfrac">
    <m:f>
      <m:num>
        <xsl:apply-templates select="*[1]"/>
      </m:num>
      <m:den>
        <xsl:apply-templates select="*[2]"/>
      </m:den>
    </m:f>
  </xsl:template>
  <xsl:template match="mml:msqrt">
    <m:rad>
      <m:radPr>
        <m:degHide m:val="on"/>
      </m:radPr>
      <m:deg/>
      <m:e>
        <xsl:apply-templates select="*"/>
      </m:e>
    </m:rad>
  </xsl:template>
  <xsl:template match="mml:mroot">
    <m:rad>
      <m:deg>
        <xsl:apply-templates select="*[2]"/>
      </m:deg>
      <m:e>
        <xsl:apply-templates select="*[1]"/>
      </m:e>
    </m:rad>
  </xsl:template>
  <xsl:template match="mml:mfenced">
    <m:d>
      <m:e>
        <xsl:apply-templates select="*"/>
      </m:e>
    </m:d>
  </xsl:template>
  <xsl:template match="mml:mrow">
    <xsl:apply-templates select="*"/>
  </xsl:template>
  <xsl:template match="mml:mtext">
    <m:r>
      <m:t><xsl:value-of select="."/></m:t>
    </m:r>
  </xsl:template>
  <!-- Fallback for unknown tags -->
  <xsl:template match="*">
    <xsl:apply-templates select="*"/>
  </xsl:template>
</xsl:stylesheet>`;
